  - name: Install Apache Web Server
    package:
      name: "httpd"
      state: present

  - name: Copy index.html
    copy:
      content: "Load Balancer Demo !! {{ansible_hostname}}"
      dest: "/var/www/html/index.html"
    tags: webgit

  - name: service httpd
    service:
      name: httpd
      state: started
